{
	"camera360v5":{
		"device":"SamsungGear360",
		"address":"20110 Pleasant View. Groveland, CA 95321",
		"tour":[{
				"index":1,
				"path":"./static_assets/pinelakemountain/part2/360_0484_Stitch_XHC.JPG",
				"front":10,
				"back":2,
				"right":8
			},{
				"index":2,
				"path":"./static_assets/pinelakemountain/part2/360_0485_Stitch_XHC.JPG",
				"front":1,
				"right":3,
				"left":7
			},{
				"index":3,
				"path":"./static_assets/pinelakemountain/part2/360_0486_Stitch_XHC.JPG",
				"right":4,
				"left":2
			},{
				"index":4,
				"path":"./static_assets/pinelakemountain/part2/360_0487_Stitch_XHC.JPG",
				"front":5,
				"left":3
			},{
				"index":5,
				"path":"./static_assets/pinelakemountain/part2/360_0488_Stitch_XHC.JPG",
				"front":6,
				"back":4
			},{
				"index":6,
				"path":"./static_assets/pinelakemountain/part2/360_0489_Stitch_XHC.JPG",
				"back":5,
				"left":9
			},{
				"index":7,
				"path":"./static_assets/pinelakemountain/part2/360_0490_Stitch_XHC.JPG",
				"right":2
			},
			{
				"index":8,
				"path":"./static_assets/pinelakemountain/part2/360_0491_Stitch_XHC.JPG",
				"front":9,
				"left":1
			},
			{
				"index":9,
				"path":"./static_assets/pinelakemountain/part2/360_0492_Stitch_XHC.JPG",
				"back":8,
				"left":10,
				"right":6
			},
			{
				"index":10,
				"path":"./static_assets/pinelakemountain/part2/360_0493_Stitch_XHC.JPG",
				"back":1,
				"left":11,
				"right":9
			},
			{
				"index":11,
				"path":"./static_assets/pinelakemountain/part2/360_0494_Stitch_XHC.JPG",
				"front":12,
				"back":16,
				"left":13,
				"right":10
			},
			{
				"index":12,
				"path":"./static_assets/pinelakemountain/part2/360_0495_Stitch_XHC.JPG",
				"back":11
			},
			{
				"index":13,
				"path":"./static_assets/pinelakemountain/part2/360_0496_Stitch_XHC.JPG",
				"right":11,
				"left":14,
				"back":15
			},
			{
				"index":14,
				"path":"./static_assets/pinelakemountain/part2/360_0497_Stitch_XHC.JPG",
				"right":13
			},
			{
				"index":15,
				"path":"./static_assets/pinelakemountain/part2/360_0498_Stitch_XHC.JPG",
				"front":13
			},
			{
				"index":16,
				"path":"./static_assets/pinelakemountain/part2/360_0499_Stitch_XHC.JPG",
				"front":11
			}
		]
	}
}